[tool.poetry]
name = "prompt-engineering-lawyers"
version = "0.1.0"
description = ""
authors = ["houfu <houfu@lovelawrobots.com>"]
readme = "README.md"
packages = [{include = "prompt_engineering_lawyers"}]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.22.0"
openai = "^0.27.6"
langchain = "^0.0.167"
tiktoken = "^0.4.0"
streamlit-book = "^0.7.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
